### ISSUE TITLE
Thank you, thank you, thank you!

### ISSUE THREAD

**Issue by MalikRumi** [simonw/simonwillisonblog#16]
I just got through realizing I can't make Elasticsearch work on my schema because I am too dependent on relations ES can't handle. Out of despair more than hope, I put 'postgres facet search' into Google, and there you were to my rescue!
If I may be somewhat greedy, and ask for a little more like Oliver Twist, what about integrating HStore into this project?

**Comment by simonw** [comment]
I'm using PostgreSQL JSON a bit which is similar to hstore but more flexible. I'm actually considering combining my three content types (entry, blog mark, quotation) into a single table using a JSON column for the fields that differ but I doubt I'll get to that any time soon - most of my side project hacking time is going to https://github.com/simonw/datasette at the moment.
