### ISSUE TITLE
Invalid Atom feed

### ISSUE THREAD

**Issue by NicolasLM** [simonw/simonwillisonblog#17]
The Atom feed of your blog is invalid. The `published` element is optional while `updated` is mandatory. 

Citing RFC 4287:
> atom:entry elements MUST contain exactly one atom:updated element

PS: I feel a bit silly to open an issue on someone else's blog.

**Comment by simonw** [comment]
Thanks for spotting this.

**Comment by simonw** [comment]
Valid now: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fsimonwillison.net%2Fatom%2Feverything%2F
