### ISSUE TITLE
Add year headers to tag index pages

### ISSUE THREAD

**Issue by simonw** [simonw/simonwillisonblog#18]
https://simonwillison.net/tags/aws/ would be more interesting with year headers, something like this:

<img width="888" alt="Simon_Willison_on_aws" src="https://user-images.githubusercontent.com/9599/56311200-4b242680-6102-11e9-8840-3fe629eeb8aa.png">

**Comment by RingoKid** [comment]
Hi. I could try to do this. Do you allow open source contribution?
